name = "«quantumInfo»"
defaultTargets = ["«QuantumInfo»"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "ClassicalInfo"

[[lean_lib]]
name = "QuantumInfo"
